# Generated by Django 4.1.2 on 2022-10-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
