# Generated by Django 4.1.2 on 2022-10-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_categoria_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
