# Generated by Django 4.1.2 on 2023-09-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_compra', models.IntegerField()),
                ('codigo_prod', models.IntegerField(null=True)),
                ('produtos', models.CharField(blank=True, max_length=1000, null=True)),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('preco_uni', models.FloatField()),
                ('estoque', models.IntegerField()),
            ],
        ),
    ]
