# Generated by Django 4.1.2 on 2023-09-15 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='liquido',
            field=models.FloatField(null=True),
        ),
    ]
